---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-web
    release: {{ .Release.Name }}
  name: "app-web-{{ .Release.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-web
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: app-web
        release: {{ .Release.Name }}
    spec:
      containers:
        - image: "{{ .Values.image_frontend.repository }}:{{ .Values.image_frontend.tag | default .Values.image.tag }}"
          name: frontend
          ports:
            - containerPort: 80
              name: http
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: app-web
    release: {{ .Release.Name }}
  name: "app-web-{{ .Release.Name }}"
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: http
      nodePort: 30080
  selector:
    app: app-web
    release: {{ .Release.Name }}
  type: NodePort
